In [1]:
print("I love Python!")

I love Python!


In [7]:
s = "S"
w = "Hello Karanlad"

In [8]:
type(s)

str

In [9]:
type(w)

str

In [10]:
s = " "
type(s)

str

In [11]:
len(w)

14

In [12]:
w[8]

'r'

In [14]:
w[5:13]

' Karanla'

In [15]:
w[8:]

'ranlad'

In [16]:
w[7:-3]

'aran'

In [17]:
w[::5]

'H n'

In [18]:
5 "+" 9

SyntaxError: invalid syntax (3736906190.py, line 1)

In [19]:
'don\'t'

"don't"

In [20]:
str_a = "I am hungry! "
str_b = "You too!"

print(str_a + str_b)

I am hungry! You too!


In [21]:
print("x = " + str(x))

NameError: name 'x' is not defined

In [22]:
w.upper()

'HELLO KARANLAD'

In [23]:
w.replace("World", "dear")

'Hello Karanlad'

In [24]:
w.replace("karan", "Berkeley")

'Hello Karanlad'

In [25]:
name = "UC Berkeley"
country = 'IND'

print("%s is a great school in %s!"%(name, country))

UC Berkeley is a great school in IND!


In [26]:
print(f"{name} is a great school in {country}.")

UC Berkeley is a great school in IND.


In [27]:
list_1 = [1, 6,7, 3]
list_1

[1, 6, 7, 3]

In [29]:
list_2 = ['Hello', 'karan']
list_2

['Hello', 'karan']

In [31]:
list_3 = [1, 4,1, 3, 'karan', 'banana']
list_3

[1, 4, 1, 3, 'karan', 'banana']

In [32]:
list_4 = [list_1, list_2]
list_4

[[1, 6, 7, 3], ['Hello', 'karan']]

In [33]:
list_3[5]

'banana'

In [34]:
list_3[:5]

[1, 4, 1, 3, 'karan']

In [35]:
list_4[0]

[1, 6, 7, 3]

In [36]:
len(list_3)

6

In [37]:
list_3 + list_2

[1, 4, 1, 3, 'karan', 'banana', 'Hello', 'karan']

In [38]:
list_1.append(5)
list_1

[1, 6, 7, 3, 5]

In [40]:
list_1.insert(2,'cake')
list_1

[1, 6, 'cake', 'center', 7, 3, 5]

In [41]:
del list_1[3]
list_1

[1, 6, 'cake', 7, 3, 5]

In [45]:
list_4.append(8)
list_4

[[1, 6, 'cake', 7, 3, 5], ['Hello', 'karan'], 8, 8, 8]

In [46]:
5 in list_1

True

In [47]:
list('Hello karan')

['H', 'e', 'l', 'l', 'o', ' ', 'k', 'a', 'r', 'a', 'n']

In [48]:
tuple_1 = (1, 2, 3, 6)
tuple_1

(1, 2, 3, 6)

In [49]:
len(tuple_1)

4

In [50]:
tuple_1[1:2]

(2,)

In [51]:
tuple_1.count(4)

0

In [52]:
list_1 = [1, 2, 3,4,5]
list_1[2] = 1
list_1

[1, 2, 1, 4, 5]

In [53]:
# a game  list
['cricket', 'football', 'gaming']

['cricket', 'football', 'gaming']

In [54]:
# a list of (game, number) pairs
[('cricket',1),('football',2),( 'gaming',4)]

[('cricket', 1), ('football', 2), ('gaming', 4)]

In [55]:
a, b, c = list_1
print(a, b, c)

ValueError: too many values to unpack (expected 3)

In [56]:
list_2 = 2, 4, 5
list_2

(2, 4, 5)

In [57]:
{5, 2, 3, 1, 6, 4, 2}

{1, 2, 3, 4, 5, 6}

In [58]:
set_1 = set([1, 2, 2, 5,6,6,8, 2, 1, 2])
set_1

{1, 2, 5, 6, 8}

In [59]:
set('Banana')

{'B', 'a', 'n'}

In [61]:
set_2 = set((2, 4, 7,6,7,6, 5, 2))
set_2

{2, 4, 5, 6, 7}

In [62]:
print(set_1)
print(set_2)

{1, 2, 5, 6, 8}
{2, 4, 5, 6, 7}


In [63]:
set_1.union(set_2)

{1, 2, 4, 5, 6, 7, 8}

In [64]:
set_1.intersection(set_2)

{2, 5, 6}

In [65]:
set_1.issubset({1, 2, 3, 3, 4, 5})

False

In [66]:
set_1.issubset({ 2, 3, 3, })

False

In [67]:
dict_1 = {'apple':3, 'oragne':4, 'pear':2}
dict_1

{'apple': 3, 'oragne': 4, 'pear': 2}

In [68]:
dict_1['apple']

3

In [69]:
dict_1.keys()

dict_keys(['apple', 'oragne', 'pear'])

In [70]:
dict_1.values()

dict_values([3, 4, 2])

In [71]:
len(dict_1)

3

In [72]:
dict([("UC Berkeley", "ind"), ('Oxford', 'UK')])

{'UC Berkeley': 'ind', 'Oxford': 'UK'}

In [74]:
import numpy as np
x = np.array([1, 4, 3])
x

array([1, 4, 3])

In [75]:
y = np.array([[1, 4, 3], [9, 2, 7]])
y

array([[1, 4, 3],
       [9, 2, 7]])

In [76]:
y.shape

(2, 3)

In [77]:
y.size

6

In [78]:
z = np.arange(1,100, 1)
z

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [79]:
np.arange(0.5, 3, 1.5)

array([0.5, 2. ])

In [80]:
np.linspace(3, 9, 3)

array([3., 6., 9.])

In [81]:

x[1]

4

In [82]:

x[1:]

array([4, 3])

In [83]:
y[:, [0, 2]]

array([[1, 3],
       [9, 7]])

In [84]:
np.zeros((5,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [85]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [86]:
np.empty(5)

array([2.12199579e-314, 1.32882234e-258, 6.67976753e-321, 1.46417710e-312,
       1.23451208e-311])

In [87]:
a = np.arange(1, 6)
a

array([1, 2, 3, 4, 5])

In [88]:
a[2] = 5
a

array([1, 2, 5, 4, 5])

In [89]:
b = np.zeros((2, 2))
b[0, 0] = 0
b[0, 1] = 7
b[1, 0] = 9
b[1, 1] = 4
b

array([[0., 7.],
       [9., 4.]])

In [90]:
b + 7

array([[ 7., 14.],
       [16., 11.]])

In [91]:
b / 0

C:\Users\91997\AppData\Local\Temp\ipykernel_7656\3917030537.py:1: RuntimeWarning: divide by zero encountered in true_divide
  b / 0
C:\Users\91997\AppData\Local\Temp\ipykernel_7656\3917030537.py:1: RuntimeWarning: invalid value encountered in true_divide
  b / 0


array([[nan, inf],
       [inf, inf]])

In [92]:
b / 9

array([[0.        , 0.77777778],
       [1.        , 0.44444444]])

In [93]:
b = np.array([[1, 6], [7, 4]])
d = np.array([[9, 4], [5, 0]])

In [94]:
b+d

array([[10, 10],
       [12,  4]])

In [95]:
b - d

array([[-8,  2],
       [ 2,  4]])

In [96]:
b / d

C:\Users\91997\AppData\Local\Temp\ipykernel_7656\168894821.py:1: RuntimeWarning: divide by zero encountered in true_divide
  b / d


array([[0.11111111, 1.5       ],
       [1.4       ,        inf]])

In [97]:
b.T

array([[1, 7],
       [6, 4]])

In [98]:
x = np.array([1, 2, 4, 5,7,4])
y = np.array([0, 2, 3, 1, 2, 3])

In [99]:
x > 3

array([False, False,  True,  True,  True,  True])

In [100]:
x > y

array([ True, False,  True,  True,  True,  True])

In [101]:
x[x > 3] = 0
x

array([1, 2, 0, 0, 0, 0])