In [5]:
f = open('./test.txt', 'r')
content = f.read()
f.close()
print(content)

This is line 0
This is line 1
This is line 2
This is line 3
This is line 4
This is another line



In [6]:
f = open('./test.txt', 'r')
contents = f.readlines()
f.close()
print(contents)

['This is line 0\n', 'This is line 1\n', 'This is line 2\n', 'This is line 3\n', 'This is line 4\n', 'This is another line\n']


In [7]:
import numpy as np

In [12]:
arr = np.array([[2.20, 2.2, 3.00], [5.1, 5.65, 5.42]])
arr

array([[2.2 , 2.2 , 3.  ],
       [5.1 , 5.65, 5.42]])

In [13]:
np.savetxt('my_arr.txt', arr, fmt='%.2f', header = 'Col1 Col2 Col3')

In [18]:
my_arr = np.loadtxt('my_arr.txt')
my_arr

array([[2.2 , 2.2 , 3.  ],
       [5.1 , 5.65, 5.42]])

In [20]:
my_csv = np.loadtxt('./test.csv', delimiter=',')
my_csv[:4, :]

array([[0.63, 0.53, 0.07, 0.15, 0.44],
       [0.64, 0.22, 0.95, 0.32, 0.61],
       [0.67, 0.18, 0.55, 0.65, 0.71],
       [0.57, 0.92, 0.57, 0.61, 0.58]])